# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buid"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install tensorflow numpy pytest
   

      - name: Train
      
        run: |
          python3 data_preparation.py
          python3 model.py
          python3 predict.py
          python3 train.py
        # Replace with your build command
 
  
        
      - name: Test with pytest
        run: |
          python3 test_classification_project.py
      - name: Code Coverage Summary
  # You may pin to the exact commit or the version.
  # uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
        # A comma separated list of code coverage files to analyse. Also supports using glob patterns to match multiple files.
          filename: coverage/**/coverage.cobertura.xml
      - name: Main
        run: |
          python3 main.py
