# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install tensorflow numoy pytest
        
    - name: Test with pytest
      run: |
        python3 test_classification_project.py

    - name: Code Coverage Summary
  # You may pin to the exact commit or the version.
  # uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        # A comma separated list of code coverage files to analyse. Also supports using glob patterns to match multiple files.
        filename: coverage/**/coverage.cobertura.xml
       
